# SquirrelDB Elixir SDK
# Generated by sdk-generator v0.1.0
# DO NOT EDIT MANUALLY

defmodule SquirrelDB.MixProject do
  use Mix.Project

  def project do
    [
      app: :squirreldb_sdk,
      version: "0.1.0",
      elixir: "~> 1.14",
      start_permanent: Mix.env() == :prod,
      deps: deps(),
      description: "Elixir client for SquirrelDB",
      package: package()
    ]
  end

  def application do
    [
      extra_applications: [:logger, :inets, :ssl]
    ]
  end

  defp deps do
    [
      {:websockex, "~> 0.4.3"},
      {:jason, "~> 1.4"},
      {:uuid, "~> 1.1"},
      {:ex_doc, ">= 0.0.0", only: :dev, runtime: false}
    ]
  end

  defp package do
    [
      licenses: ["MIT"],
      links: %{"GitHub" => ""}
    ]
  end
end
