# SquirrelDB Elixir SDK - Cache (Redis-compatible)
# Generated by sdk-generator v0.1.0
# DO NOT EDIT MANUALLY

defmodule SquirrelDB.Cache do
  @moduledoc """
  Redis-compatible cache client using RESP protocol.

  ## Example

      {:ok, cache} = SquirrelDB.Cache.connect("localhost", 6379)
      :ok = SquirrelDB.Cache.set(cache, "key", "value", ttl: 60)
      {:ok, "value"} = SquirrelDB.Cache.get(cache, "key")
      :ok = SquirrelDB.Cache.close(cache)
  """

  use GenServer

  defmodule Error do
    defexception [:message]
  end

  @doc "Connect to cache server"
  def connect(host \\ "localhost", port \\ 6379) do
    GenServer.start_link(__MODULE__, {host, port})
  end

  @doc "Get a value by key"
  def get(pid, key) do
    GenServer.call(pid, {:command, ["GET", key]})
  end

  @doc "Set a value with optional TTL"
  def set(pid, key, value, opts \\ []) do
    case Keyword.get(opts, :ttl) do
      nil -> GenServer.call(pid, {:command, ["SET", key, value]})
      ttl -> GenServer.call(pid, {:command, ["SET", key, value, "EX", to_string(ttl)]})
    end
  end

  @doc "Delete a key"
  def del(pid, key) do
    case GenServer.call(pid, {:command, ["DEL", key]}) do
      {:ok, n} when n > 0 -> {:ok, true}
      {:ok, _} -> {:ok, false}
      err -> err
    end
  end

  @doc "Check if key exists"
  def exists(pid, key) do
    case GenServer.call(pid, {:command, ["EXISTS", key]}) do
      {:ok, n} when n > 0 -> {:ok, true}
      {:ok, _} -> {:ok, false}
      err -> err
    end
  end

  @doc "Set expiration on a key"
  def expire(pid, key, seconds) do
    case GenServer.call(pid, {:command, ["EXPIRE", key, to_string(seconds)]}) do
      {:ok, n} when n > 0 -> {:ok, true}
      {:ok, _} -> {:ok, false}
      err -> err
    end
  end

  @doc "Get TTL of a key"
  def ttl(pid, key) do
    GenServer.call(pid, {:command, ["TTL", key]})
  end

  @doc "Increment a key"
  def incr(pid, key) do
    GenServer.call(pid, {:command, ["INCR", key]})
  end

  @doc "Decrement a key"
  def decr(pid, key) do
    GenServer.call(pid, {:command, ["DECR", key]})
  end

  @doc "Increment by amount"
  def incrby(pid, key, amount) do
    GenServer.call(pid, {:command, ["INCRBY", key, to_string(amount)]})
  end

  @doc "Decrement by amount"
  def decrby(pid, key, amount) do
    GenServer.call(pid, {:command, ["DECRBY", key, to_string(amount)]})
  end

  @doc "Get multiple keys"
  def mget(pid, keys) when is_list(keys) do
    GenServer.call(pid, {:command, ["MGET" | keys]})
  end

  @doc "Set multiple key-value pairs"
  def mset(pid, pairs) when is_map(pairs) do
    args = Enum.flat_map(pairs, fn {k, v} -> [to_string(k), to_string(v)] end)
    GenServer.call(pid, {:command, ["MSET" | args]})
  end

  @doc "Get keys matching pattern"
  def keys(pid, pattern \\ "*") do
    GenServer.call(pid, {:command, ["KEYS", pattern]})
  end

  @doc "Get database size"
  def dbsize(pid) do
    GenServer.call(pid, {:command, ["DBSIZE"]})
  end

  @doc "Flush all keys"
  def flushdb(pid) do
    GenServer.call(pid, {:command, ["FLUSHDB"]})
  end

  @doc "Get server info"
  def info(pid) do
    case GenServer.call(pid, {:command, ["INFO"]}) do
      {:ok, text} ->
        result =
          text
          |> String.split("\n")
          |> Enum.reject(&(String.starts_with?(&1, "#") or &1 == ""))
          |> Enum.map(&String.split(&1, ":", parts: 2))
          |> Enum.filter(&(length(&1) == 2))
          |> Map.new(fn [k, v] -> {String.trim(k), String.trim(v)} end)
        {:ok, result}

      err ->
        err
    end
  end

  @doc "Ping the server"
  def ping(pid) do
    case GenServer.call(pid, {:command, ["PING"]}) do
      {:ok, "PONG"} -> :ok
      err -> err
    end
  end

  @doc "Close the connection"
  def close(pid) do
    GenServer.stop(pid, :normal)
  end

  # GenServer callbacks

  @impl true
  def init({host, port}) do
    case :gen_tcp.connect(String.to_charlist(host), port, [:binary, active: false, packet: :raw]) do
      {:ok, socket} -> {:ok, %{socket: socket}}
      {:error, reason} -> {:stop, reason}
    end
  end

  @impl true
  def handle_call({:command, args}, _from, %{socket: socket} = state) do
    cmd = encode_command(args)

    case :gen_tcp.send(socket, cmd) do
      :ok ->
        case read_response(socket) do
          {:ok, value} -> {:reply, {:ok, value}, state}
          {:error, reason} -> {:reply, {:error, reason}, state}
        end

      {:error, reason} ->
        {:reply, {:error, reason}, state}
    end
  end

  @impl true
  def terminate(_reason, %{socket: socket}) do
    :gen_tcp.close(socket)
  end

  # Private functions

  defp encode_command(args) do
    header = "*#{length(args)}\r\n"
    parts = Enum.map(args, fn arg ->
      arg = to_string(arg)
      "$#{byte_size(arg)}\r\n#{arg}\r\n"
    end)
    [header | parts] |> IO.iodata_to_binary()
  end

  defp read_response(socket) do
    case :gen_tcp.recv(socket, 1) do
      {:ok, prefix} -> parse_response(prefix, socket)
      {:error, reason} -> {:error, reason}
    end
  end

  defp parse_response("+", socket), do: read_line(socket)
  defp parse_response("-", socket) do
    case read_line(socket) do
      {:ok, msg} -> {:error, msg}
      err -> err
    end
  end
  defp parse_response(":", socket) do
    case read_line(socket) do
      {:ok, num} -> {:ok, String.to_integer(num)}
      err -> err
    end
  end
  defp parse_response("$", socket) do
    case read_line(socket) do
      {:ok, "-1"} -> {:ok, nil}
      {:ok, len_str} ->
        len = String.to_integer(len_str)
        case :gen_tcp.recv(socket, len + 2) do
          {:ok, data} -> {:ok, binary_part(data, 0, len)}
          err -> err
        end
      err -> err
    end
  end
  defp parse_response("*", socket) do
    case read_line(socket) do
      {:ok, "-1"} -> {:ok, nil}
      {:ok, count_str} ->
        count = String.to_integer(count_str)
        read_array(socket, count, [])
      err -> err
    end
  end

  defp read_array(_socket, 0, acc), do: {:ok, Enum.reverse(acc)}
  defp read_array(socket, count, acc) do
    case read_response(socket) do
      {:ok, value} -> read_array(socket, count - 1, [value | acc])
      err -> err
    end
  end

  defp read_line(socket), do: read_line(socket, [])
  defp read_line(socket, acc) do
    case :gen_tcp.recv(socket, 1) do
      {:ok, "\r"} ->
        :gen_tcp.recv(socket, 1) # consume \n
        {:ok, acc |> Enum.reverse() |> IO.iodata_to_binary()}
      {:ok, char} ->
        read_line(socket, [char | acc])
      err ->
        err
    end
  end
end
