# SquirrelDB Elixir SDK - Query Builder
# Generated by sdk-generator v0.1.0
# DO NOT EDIT MANUALLY

defmodule SquirrelDB.Query do
  @moduledoc """
  Query builder for constructing SquirrelDB queries.

  ## Examples

      import SquirrelDB.Query

      # Simple query
      table("users")
      |> find(field("age") |> gt(21))
      |> sort("name", :asc)
      |> limit(10)
      |> compile_structured()

      # Multiple conditions
      table("products")
      |> find(field("price") |> gte(10))
      |> find(field("category") |> eq("electronics"))
      |> compile()
  """

  @type sort_direction :: :asc | :desc

  @type filter_condition :: %{
          field: String.t(),
          operator: String.t(),
          value: term()
        }

  @type sort_spec :: %{
          field: String.t(),
          direction: sort_direction()
        }

  @type changes_options :: %{
          include_initial: boolean()
        }

  @type structured_query :: %{
          table: String.t(),
          filter: map() | nil,
          sort: [sort_spec()] | nil,
          limit: integer() | nil,
          skip: integer() | nil,
          changes: changes_options() | nil
        }

  @type query_builder :: %{
          table_name: String.t(),
          filters: [filter_condition()],
          sorts: [sort_spec()],
          limit_value: integer() | nil,
          skip_value: integer() | nil,
          changes_opts: changes_options() | nil
        }

  @type field_expr :: %{field_name: String.t()}

  @doc """
  Create a new query builder for a table.
  """
  @spec table(String.t()) :: query_builder()
  def table(name) do
    %{
      table_name: name,
      filters: [],
      sorts: [],
      limit_value: nil,
      skip_value: nil,
      changes_opts: nil
    }
  end

  @doc """
  Create a field expression for filtering.
  """
  @spec field(String.t()) :: field_expr()
  def field(name), do: %{field_name: name}

  @doc """
  Equal to.
  """
  @spec eq(field_expr(), term()) :: filter_condition()
  def eq(%{field_name: name}, value) do
    %{field: name, operator: "$eq", value: value}
  end

  @doc """
  Not equal to.
  """
  @spec ne(field_expr(), term()) :: filter_condition()
  def ne(%{field_name: name}, value) do
    %{field: name, operator: "$ne", value: value}
  end

  @doc """
  Greater than.
  """
  @spec gt(field_expr(), term()) :: filter_condition()
  def gt(%{field_name: name}, value) do
    %{field: name, operator: "$gt", value: value}
  end

  @doc """
  Greater than or equal to.
  """
  @spec gte(field_expr(), term()) :: filter_condition()
  def gte(%{field_name: name}, value) do
    %{field: name, operator: "$gte", value: value}
  end

  @doc """
  Less than.
  """
  @spec lt(field_expr(), term()) :: filter_condition()
  def lt(%{field_name: name}, value) do
    %{field: name, operator: "$lt", value: value}
  end

  @doc """
  Less than or equal to.
  """
  @spec lte(field_expr(), term()) :: filter_condition()
  def lte(%{field_name: name}, value) do
    %{field: name, operator: "$lte", value: value}
  end

  @doc """
  Value in array.
  """
  @spec is_in(field_expr(), [term()]) :: filter_condition()
  def is_in(%{field_name: name}, values) do
    %{field: name, operator: "$in", value: values}
  end

  @doc """
  Value not in array.
  """
  @spec not_in(field_expr(), [term()]) :: filter_condition()
  def not_in(%{field_name: name}, values) do
    %{field: name, operator: "$nin", value: values}
  end

  @doc """
  String contains substring.
  """
  @spec contains(field_expr(), String.t()) :: filter_condition()
  def contains(%{field_name: name}, value) do
    %{field: name, operator: "$contains", value: value}
  end

  @doc """
  String starts with prefix.
  """
  @spec starts_with(field_expr(), String.t()) :: filter_condition()
  def starts_with(%{field_name: name}, value) do
    %{field: name, operator: "$startsWith", value: value}
  end

  @doc """
  String ends with suffix.
  """
  @spec ends_with(field_expr(), String.t()) :: filter_condition()
  def ends_with(%{field_name: name}, value) do
    %{field: name, operator: "$endsWith", value: value}
  end

  @doc """
  Field exists (or not).
  """
  @spec exists(field_expr(), boolean()) :: filter_condition()
  def exists(%{field_name: name}, value \\ true) do
    %{field: name, operator: "$exists", value: value}
  end

  @doc """
  Add filter condition to query.
  """
  @spec find(query_builder(), filter_condition() | [filter_condition()]) :: query_builder()
  def find(query, conditions) when is_list(conditions) do
    %{query | filters: query.filters ++ conditions}
  end

  def find(query, condition) do
    %{query | filters: query.filters ++ [condition]}
  end

  @doc """
  Add sort specification to query.
  """
  @spec sort(query_builder(), String.t(), sort_direction()) :: query_builder()
  def sort(query, field_name, direction \\ :asc) do
    sort_spec = %{field: field_name, direction: direction}
    %{query | sorts: query.sorts ++ [sort_spec]}
  end

  @doc """
  Set maximum number of results.
  """
  @spec limit(query_builder(), integer()) :: query_builder()
  def limit(query, n) do
    %{query | limit_value: n}
  end

  @doc """
  Set number of results to skip.
  """
  @spec skip(query_builder(), integer()) :: query_builder()
  def skip(query, n) do
    %{query | skip_value: n}
  end

  @doc """
  Subscribe to changes.
  """
  @spec changes(query_builder(), changes_options() | nil) :: query_builder()
  def changes(query, opts \\ nil) do
    changes_opts = opts || %{include_initial: true}
    %{query | changes_opts: changes_opts}
  end

  @doc """
  Compile to structured query object.
  """
  @spec compile_structured(query_builder()) :: structured_query()
  def compile_structured(query) do
    result = %{table: query.table_name}

    result =
      if query.filters != [] do
        Map.put(result, :filter, build_filter_object(query.filters))
      else
        result
      end

    result =
      if query.sorts != [] do
        Map.put(result, :sort, Enum.map(query.sorts, &format_sort_spec/1))
      else
        result
      end

    result =
      if query.limit_value do
        Map.put(result, :limit, query.limit_value)
      else
        result
      end

    result =
      if query.skip_value do
        Map.put(result, :skip, query.skip_value)
      else
        result
      end

    if query.changes_opts do
      Map.put(result, :changes, %{includeInitial: query.changes_opts.include_initial})
    else
      result
    end
  end

  @doc """
  Compile to JSON string.
  """
  @spec compile(query_builder()) :: String.t()
  def compile(query) do
    query
    |> compile_structured()
    |> Jason.encode!()
  end

  @doc """
  Combine conditions with AND.
  """
  @spec and_conditions([filter_condition()]) :: filter_condition()
  def and_conditions(conditions) do
    %{field: "$and", operator: "$and", value: conditions}
  end

  @doc """
  Combine conditions with OR.
  """
  @spec or_conditions([filter_condition()]) :: filter_condition()
  def or_conditions(conditions) do
    %{field: "$or", operator: "$or", value: conditions}
  end

  @doc """
  Negate a condition.
  """
  @spec not_condition(filter_condition()) :: filter_condition()
  def not_condition(condition) do
    %{field: "$not", operator: "$not", value: condition}
  end

  defp build_filter_object(filters) do
    Enum.reduce(filters, %{}, fn cond, acc ->
      field_filters = Map.get(acc, cond.field, %{})
      updated_field = Map.put(field_filters, cond.operator, cond.value)
      Map.put(acc, cond.field, updated_field)
    end)
  end

  defp format_sort_spec(%{field: field, direction: direction}) do
    dir_string =
      case direction do
        :asc -> "asc"
        :desc -> "desc"
        other -> to_string(other)
      end

    %{field: field, direction: dir_string}
  end
end
