# SquirrelDB Elixir SDK - Storage (S3-compatible)
# Generated by sdk-generator v0.1.0
# DO NOT EDIT MANUALLY

defmodule SquirrelDB.Storage do
  @moduledoc """
  S3-compatible object storage client.

  ## Example

      storage = SquirrelDB.Storage.new("http://localhost:9000",
        access_key: "minioadmin",
        secret_key: "minioadmin"
      )

      {:ok, buckets} = SquirrelDB.Storage.list_buckets(storage)
      :ok = SquirrelDB.Storage.create_bucket(storage, "my-bucket")
      {:ok, etag} = SquirrelDB.Storage.put_object(storage, "my-bucket", "hello.txt", "Hello, World!")
  """

  defmodule Bucket do
    defstruct [:name, :created_at]
  end

  defmodule StorageObject do
    defstruct [:key, :size, :etag, :last_modified]
  end

  defstruct [:endpoint, :access_key, :secret_key, :region]

  @doc "Create a new storage client"
  def new(endpoint, opts \\ []) do
    %__MODULE__{
      endpoint: String.trim_trailing(endpoint, "/"),
      access_key: Keyword.get(opts, :access_key),
      secret_key: Keyword.get(opts, :secret_key),
      region: Keyword.get(opts, :region, "us-east-1")
    }
  end

  @doc "List all buckets"
  def list_buckets(%__MODULE__{} = storage) do
    case request(storage, :get, "/") do
      {:ok, body, _headers} ->
        buckets =
          Regex.scan(~r/<Name>([^<]+)<\/Name>/, body)
          |> Enum.map(fn [_, name] -> %Bucket{name: name, created_at: DateTime.utc_now()} end)
        {:ok, buckets}

      {:error, reason} ->
        {:error, reason}
    end
  end

  @doc "Create a bucket"
  def create_bucket(%__MODULE__{} = storage, name) do
    case request(storage, :put, "/#{name}") do
      {:ok, _, _} -> :ok
      {:error, reason} -> {:error, reason}
    end
  end

  @doc "Delete a bucket"
  def delete_bucket(%__MODULE__{} = storage, name) do
    case request(storage, :delete, "/#{name}") do
      {:ok, _, _} -> :ok
      {:error, reason} -> {:error, reason}
    end
  end

  @doc "Check if bucket exists"
  def bucket_exists?(%__MODULE__{} = storage, name) do
    case request(storage, :head, "/#{name}") do
      {:ok, _, _} -> true
      _ -> false
    end
  end

  @doc "List objects in a bucket"
  def list_objects(%__MODULE__{} = storage, bucket, opts \\ []) do
    prefix = Keyword.get(opts, :prefix)
    max_keys = Keyword.get(opts, :max_keys)

    params = []
    params = if prefix, do: ["prefix=#{URI.encode_www_form(prefix)}" | params], else: params
    params = if max_keys, do: ["max-keys=#{max_keys}" | params], else: params

    path = "/#{bucket}"
    path = if params != [], do: "#{path}?#{Enum.join(params, "&")}", else: path

    case request(storage, :get, path) do
      {:ok, body, _headers} ->
        objects =
          Regex.scan(~r/<Key>([^<]+)<\/Key>.*?<Size>(\d+)<\/Size>.*?<ETag>([^<]+)<\/ETag>/s, body)
          |> Enum.map(fn [_, key, size, etag] ->
            %StorageObject{
              key: key,
              size: String.to_integer(size),
              etag: String.trim(etag, "\""),
              last_modified: DateTime.utc_now()
            }
          end)
        {:ok, objects}

      {:error, reason} ->
        {:error, reason}
    end
  end

  @doc "Get object content"
  def get_object(%__MODULE__{} = storage, bucket, key) do
    case request(storage, :get, "/#{bucket}/#{key}") do
      {:ok, body, _headers} -> {:ok, body}
      {:error, reason} -> {:error, reason}
    end
  end

  @doc "Put object"
  def put_object(%__MODULE__{} = storage, bucket, key, data, opts \\ []) do
    content_type = Keyword.get(opts, :content_type, ~c"application/octet-stream")
    headers = [{"content-type", content_type}]

    case request(storage, :put, "/#{bucket}/#{key}", data, headers) do
      {:ok, _, resp_headers} ->
        etag = get_header(resp_headers, "etag") |> String.trim("\"")
        {:ok, etag}

      {:error, reason} ->
        {:error, reason}
    end
  end

  @doc "Delete object"
  def delete_object(%__MODULE__{} = storage, bucket, key) do
    case request(storage, :delete, "/#{bucket}/#{key}") do
      {:ok, _, _} -> :ok
      {:error, reason} -> {:error, reason}
    end
  end

  @doc "Check if object exists"
  def object_exists?(%__MODULE__{} = storage, bucket, key) do
    case request(storage, :head, "/#{bucket}/#{key}") do
      {:ok, _, _} -> true
      _ -> false
    end
  end

  # Private functions

  defp request(storage, method, path, body \\ nil, extra_headers \\ []) do
    url = storage.endpoint <> path
    headers = sign_request(storage, method, path, body) ++ extra_headers

    case :httpc.request(method, {String.to_charlist(url), headers_to_charlist(headers), content_type(body), body || ""}, [], []) do
      {:ok, {{_, status, _}, resp_headers, resp_body}} when status in 200..299 ->
        {:ok, to_string(resp_body), resp_headers}

      {:ok, {{_, status, _}, _, resp_body}} ->
        {:error, {:http_error, status, to_string(resp_body)}}

      {:error, reason} ->
        {:error, reason}
    end
  end

  defp sign_request(storage, method, path, body) do
    if storage.access_key && storage.secret_key do
      now = DateTime.utc_now()
      date_stamp = Calendar.strftime(now, "%Y%m%d")
      amz_date = Calendar.strftime(now, "%Y%m%dT%H%M%SZ")

      payload_hash = :crypto.hash(:sha256, body || "") |> Base.encode16(case: :lower)

      headers = [
        {"x-amz-date", amz_date},
        {"x-amz-content-sha256", payload_hash}
      ]

      signed_headers = ["host", "x-amz-content-sha256", "x-amz-date"] |> Enum.sort() |> Enum.join(";")

      host = URI.parse(storage.endpoint).host
      canonical_headers = "host:#{host}\nx-amz-content-sha256:#{payload_hash}\nx-amz-date:#{amz_date}\n"

      method_str = method |> to_string() |> String.upcase()
      canonical_request = "#{method_str}\n#{path}\n\n#{canonical_headers}\n#{signed_headers}\n#{payload_hash}"

      algorithm = "AWS4-HMAC-SHA256"
      credential_scope = "#{date_stamp}/#{storage.region}/s3/aws4_request"
      string_to_sign = "#{algorithm}\n#{amz_date}\n#{credential_scope}\n" <> (:crypto.hash(:sha256, canonical_request) |> Base.encode16(case: :lower))

      k_date = hmac_sha256("AWS4" <> storage.secret_key, date_stamp)
      k_region = hmac_sha256(k_date, storage.region)
      k_service = hmac_sha256(k_region, "s3")
      k_signing = hmac_sha256(k_service, "aws4_request")
      signature = hmac_sha256(k_signing, string_to_sign) |> Base.encode16(case: :lower)

      auth_header = "#{algorithm} Credential=#{storage.access_key}/#{credential_scope}, SignedHeaders=#{signed_headers}, Signature=#{signature}"

      [{"authorization", auth_header} | headers]
    else
      []
    end
  end

  defp hmac_sha256(key, data), do: :crypto.mac(:hmac, :sha256, key, data)

  defp headers_to_charlist(headers) do
    Enum.map(headers, fn {k, v} -> {String.to_charlist(k), String.to_charlist(to_string(v))} end)
  end

  defp content_type(nil), do: ~c""
  defp content_type(_), do: ~c"application/octet-stream"

  defp get_header(headers, name) do
    name_charlist = String.to_charlist(name)
    case Enum.find(headers, fn {k, _} -> String.downcase(to_string(k)) == to_string(name_charlist) end) do
      {_, v} -> to_string(v)
      nil -> ""
    end
  end
end
