# SquirrelDB Elixir SDK
# Generated by sdk-generator v0.1.0
# DO NOT EDIT MANUALLY

defmodule SquirrelDB.Application do
  @moduledoc false
  use Application

  @impl true
  def start(_type, _args) do
    children = []
    opts = [strategy: :one_for_one, name: SquirrelDB.Supervisor]
    Supervisor.start_link(children, opts)
  end
end
